brigade/urls.py

from django.contrib import admin
from django.urls import path, include
from frontnd import views  # Assuming your views are in the 'frontnd' app

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('frontnd.urls')),
]

frontnd/urls.py
from django.urls import path
from . import views

app_name = 'frontnd'

urlpatterns = [

    path('about/', views.about, name='about'),
    path('', views.home, name='index'),
    path('contact/', views.contact, name='contact'),
    
    ]

frontnd/models.py
from django.db import models

# Create your models here.

frontnd/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.http import HttpResponse
# Create your views here.

def about(request):
    return render(request, 'about.html')

def home(request):
    return render(request, 'index.html')

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        mail = request.POST.get('mail')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
            
        if name and mail and phone and message:  # Ensure that all fields are filled
            try:
                send_mail(
                    subject=f'Hey PantherBrigadez i am {name}',
                    message=f'Name: {name} \nPhone: {phone} \nEmail: {mail} \nMessage: {message}.',
                    from_email=mail,  # Use a valid Gmail account
                    recipient_list=['pantherbrigades@gmail.com'],  # The admin email
                    fail_silently=False,
                )
                return render(request, 'contact.html')  # Redirect to success page
            except Exception as e:
                # Return an error message if email fails to send
                return HttpResponse(f"Error sending email: {str(e)}")
        # else:
            
        #     return HttpResponse("All fields are required")
    
    return render(request, 'contact.html')  # Return contact form if not POST


frontnd/templates/contact.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <div style="overflow-x: hidden;">
    <head>
        <meta charset="utf-8">
        <title>PanthermanagementBregade</title>
        <link href="{% static 'Pages/img/pnthr.png' %}" rel="icon">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <!-- modal bootstrap -->
        <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500;600;700&family=Rubik:wght@400;500&display=swap" rel="stylesheet"> 

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{% static 'Pages/lib/animate/animate.min.css' %}" rel="stylesheet">
        <link href="{% static 'Pages/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
        <link href="{% static 'Pages/lib/lightbox/css/lightbox.min.css' %}" rel="stylesheet">


        <!-- Customized Bootstrap Stylesheet -->
        <link href="{% static 'Pages/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{% static 'Pages/css/style.css' %}" rel="stylesheet">
    </head>
    
    <body style="background-color: black; overflow-x: hidden;">

        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar & Hero Start -->
         <div class="container-fluid p-0">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent px-4 px-lg-5 py-3 py-lg-0">
                <a href="{% url 'frontnd:index' %}" class="navbar-brand p-0">
                    <h2 style="color: #031e2f; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;"><img src="{% static 'Pages/img/pnhr.png'%}" alt="">PanthermanagementBregade</h2>

                    <!-- <h5 style="color: #000000; "><img style="border-radius: 3px; width: 100%; " src="{% static 'Pages/img/pnthr.png'%}" alt="">PanthermanagementBregade</h5> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0"  style="margin-right: 95px; padding: 6px;">
                        <a href="{% url 'frontnd:index' %}" class="nav-item nav-link">Home</a>
                        <a href="{% url 'frontnd:about' %}" class="nav-item nav-link">About</a>
                        <a href="{% url 'frontnd:index' %}#service-session" class="nav-item nav-link">Services</a><br><br>
                        <div class="nav-item dropdown">
                           
                        </div>
                        <a href="{% url 'frontnd:contact' %}" class="nav-item nav-link">Contact Us</a>
                </div>
            </nav>
        </div>
        <!-- Navbar & Hero End -->

        <div class="container-fluid blog py-5" style="overflow-x: hidden;" >
            <div class="container py-5">
                <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 900px; margin-top: 270px;">
                    <h1 class="mb-1 " style="margin-top: -150px; color: #ffffff;">Contact Us </h1><br>
                    <p class="mb-0" style="font-size: 22px;  color: #ffffff; ">what you're looking for?  connect directly with us today and
                        let's co-create for you, please get in touch. Let's Talk...!!
                    </p>
                </div>
            </div>
        </div>


        
        
        
        <div class="row g-5  align-items-center" style="margin-bottom: 100px; margin-left: 10%; ">
            <div class="col-lg-6 wow fadeInLeft" data-wow-delay="0.1s" >
                <form action="" method="post" enctype="multipart/form-data" style="overflow-x: hidden;">
                    {% csrf_token %}
                    <div class="row g-3">
                        <div class="col-12">
                            <label for="" style="color: white;">Name</label>
                            <div class="form-floating">
                                <input type="text" class="form-control" name="name" id="name" required placeholder="Name">
                                <label for="name">Full Name</label>
                            </div>
                        </div>

                        <div class="col-lg-12 col-xl-6">
                            <label for="" style="color: white;">Email</label>
                            <div class="form-floating">
                                <input type="email" class="form-control" name="mail" id="email" required placeholder="email">
                                <label for="name">Email</label>
                            </div>
                        </div>
                      
                        <div class="col-lg-12 col-xl-6">
                            <label for="" style="color: white;">Phone</label>
                            <div class="form-floating">
                                <input type="phone" class="form-control" name="phone" id="phone" required placeholder="Phone">
                                <label for="phone">Phone</label>
                            </div>
                        </div>
                        
                        <div class="col-12">
                            <label for="" style="color: white;">Message</label>
                            <div class="form-floating">
                                <textarea class="form-control" placeholder="Leave a message here" name="message" required id="message" style="height: 160px"></textarea>
                                <label for="message">Message</label>
                            </div>
                        </div>
                        <div class="col-12">
                        </div>
                        
                    </div>
                    <button onclick="success()" type="submit" style=" padding: 5px; width: 120px; font-size: 25px; border-color: #065e8d; font-family: Arial, Helvetica, sans-serif; border-radius: 35px; background-color: black; color: white;">submit</button>
                </form>
            </div>
            <!-- <script>
                function success() {
                    // Fetch values when the function is called
                    let names = document.getElementById("name").value.trim();
                    let email = document.getElementById("email").value.trim();
                    let phone = document.getElementById("phone").value.trim();
                    let message = document.getElementById("message").value.trim();
            
                    if (names && email && phone && message) {

                        alert("Send Successfully! Get in touch!! :)");

                    } else {
                        
                        alert("Please fill in all required fields.");
                    }
                }
            </script> -->
            
            
        <div class="col-lg-6 wow fadeInRight" data-wow-delay="0.3s" style="margin-bottom: 50px; margin-left: 0px; overflow-x: hidden;">
            <div class="d-flex align-items-center mb-4">
               
            </div>
            <div class="d-flex align-items-center mb-4">
                <div class="bg-light d-flex align-items-center justify-content-center mb-3" style="width: 50px; height: 50px; border-radius: 50px;"><i class="fa fa-map-marker-alt fa-1.5x "></i></div>
                <div class="ms-4">
                    
                    <p class="mb-0" style="color: rgb(217, 212, 212);">Bangalore</p>
                </div>
            </div>
            <div class="d-flex align-items-center mb-4">
                <div class="bg-light d-flex align-items-center justify-content-center mb-3" style="width: 50px; height: 50px; border-radius: 50px;"><i class="fa fa-phone-alt fa-1.5x "></i></div>
                <div class="ms-4">
                    
                    <p class="mb-0" style="color: rgb(217, 212, 212);">8970041419 <span  style="margin-left: 25px; color: rgb(217, 212, 212);">9900774940</span></p>
                    
                </div>
            </div>
            <div class="d-flex align-items-center mb-4">
                <div class="bg-light d-flex align-items-center justify-content-center mb-3" style="width: 50px; height: 50px; border-radius: 50px;"><i class="fa fa-envelope-open fa-1x "></i></div>
                <div class="ms-4">
                     
                    <p class="mb-0" style="color: rgb(217, 212, 212);;"><a href="mailto:Pantherbrigadez@gmail.com">Pantherbrigadez@gmail.com</a></p>
                    
                </div>
            </div>
            <div class="d-flex align-items-center"> 
               
                <div class="d-flex" style="margin-left: 289px;">
                    <!-- <a class="btn-square btn  rounded-circle mx-1" href="https://www.facebook.com/"><i class="fab fa-facebook-f" style="width: 28px; color: white;"></i></a> -->
                    <a class="btn-square btn  rounded-circle mx-1" href="https://www.instagram.com/sty_exploreindia/"><i class="fab fa-instagram" style="width: 28px; color: white;"></i></a>
                    <!-- <a class="btn-square btn  rounded-circle mx-1" href=""><i class="fab fa-linkedin-in" style="width: 28px; color: white;"></i></a> -->
         
                </div>
            </div>
        </div >
        
        </div>



        <!-- Copyright Start -->
        <div class="container-fluid copyright py-4" style="overflow-x: hidden;">
            <div class="container">
                <div class="row g-4 align-items-center">
                    <div class="col-md-6 text-center text-md-start mb-md-0">
                        <span class="text-white"><a href="{% url 'frontnd:index' %}"><i class="fas fa-copyright text-light me-2"></i>PanthermanagementBregade</a>, All rights reserved.</span>
                    </div>
                   
                </div>
            </div>
        </div>
        <!-- Copyright End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg-square back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
    <!-- JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'Pages/lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'Pages/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'Pages/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'Pages/lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'Pages/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'Pages/lib/lightbox/js/lightbox.min.js' %}"></script>
    
    <!-- Template Javascript -->
    <script src="{% static 'Pages/js/main.js' %}"></script>
    </body>
</html>
